models:
  - name: customers
    description: Cleaned up data for our customers
    columns:
      - name: customer_id
        description: "{{doc('customers')}}"
        tests:
          - unique
          - not_null